# Generated by Django 4.2.7 on 2025-04-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_system_owner',
            field=models.BooleanField(default=False),
        ),
    ]
